### ISSUE TITLE
help using edit document API

### ISSUE THREAD

**Issue by gv-beemining** [Cloudmersive/Cloudmersive.APIClient.NodeJS.DocumentAndDataConvert#2] opened 2020-01-02 17:09 UTC
Hi im trying to use the edit document API from nodeJS but is giving me the next error, is the edit route deprecated?

 Error: cannot POST /convert/edit/begin-editing (500)

```
const fs = require('fs');
var CloudmersiveConvertApiClient = require('cloudmersive-convert-api-client');
var defaultClient = CloudmersiveConvertApiClient.ApiClient.instance;

// Configure API key authorization: Apikey
var Apikey = defaultClient.authentications['Apikey'];
Apikey.apiKey = 'key';



var apiInstance = new CloudmersiveConvertApiClient.EditDocumentApi();

var inputFile = Buffer.from(fs.readFileSync("testFile.xlsx").buffer); // File | Input file to perform the operation on.


var callback = function(error, data, response) {
  if (error) {
    console.error(error);
  } else {
    console.log('API called successfully. Returned data: ' + data);
  }
};
apiInstance.editDocumentBeginEditing(inputFile, callback);

```

**Comment by Cloudmersive** [comment] 2020-01-02 18:55
Thank you for sharing this issue.  We are investigating it and will follow up with you shortly.

**Comment by Cloudmersive** [comment] 2020-01-02 19:08
This was caused by an issue on the service side.  A fix for this issue has been deployed and is now available in production.  This issue has now been fixed.  In your example, please be sure to set your API key.

**Closed by Cloudmersive** 2020-01-02 19:08 UTC
